docs/contribute/help-translate.md
website/i18n/en.json
website/sidebars.json
website/siteConfig.js

Solve https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/103
This help translate page is still in early stage.

Add help translate link and page.

---

docs/overview/session-keys.md
docs/overview/ss58-address-format.md
docs/runtime/architecture-of-a-runtime.md
docs/runtime/macros/decl_module.md
docs/runtime/substrate-runtime-module-library.md
docs/tutorials/adding-a-module-to-your-runtime.md
website/core/Footer.js
website/pages/en/index.js
website/pages/en/who/contract-developer.js
website/pages/en/who/runtime-developer.js
website/siteConfig.js

Brand new docs URL, hopefully ready to be indexed by search

Change `crates.parity.io` to `/rustdocs/v1.0/`

---

readme.md

@shawntabrizi @JoshOrndorff You guys may be interested in the changes.

Add steps to rename a file.

---

docs/contracts/env-types.md
docs/contracts/index.md
website/sidebars.json

Rel: https://github.com/paritytech/ink/pull/108

Docs for contract runtime env types

---

docs/overview/ss58-address-format.md

But still keep Joshy's specifics of ed25519 and sr25519.

Restore Gavs writeup.

---

docs/getting-started/installing-substrate.md

Fixes: https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/153
Mostly copied from the instruction in the Substrate ReadMe (which I wrote and tested), but slightly improved in clarity and style.

Add Windows installation steps

---

docs/contracts/deploying-a-contract.md

Instantiate button no longer exists in the new UI

correct the button name

---

docs/getting-started/installing-substrate.md
docs/getting-started/using-the-substrate-scripts.md
website/versioned_docs/version-1.0.0/getting-started/installing-substrate.md
website/versioned_docs/version-1.0.0/getting-started/using-the-substrate-scripts.md

https://github.com/paritytech/substrate/issues/3067

Update "Manual Install" instructions

---

docs/tutorials/creating-a-runtime-module.md
website/versioned_docs/version-1.0.0/tutorials/creating-a-runtime-module.md

Fixes https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/169
@bkchr How do you like this? Suggestions welcome.

More details and clarification about no_std

---

docs/ecosystem/subkey.md

Closes https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/171
Update includes:
- Dependencies
- Description of `--network`
- More password and inspect examples
- More HD key derivation explanation and examples
- Message signing and verification

Update subkey page

---

docs/overview/index.md

Forgot to add a description to the commit message so here it goes:
There was a missing closing parenthesis and adding one would result on two levels which is kind of confusing, so I fixed it by adding a comma.

Fixed index.md errata

---

docs/tutorials/substrate-front-end/part-4-use-external-accounts.md

Align the tutorial with code changes made in https://github.com/substrate-developer-hub/substrate-front-end.
cc @riusricardo

Simplify part-4-* for users without extension

---

docs/tutorials/creating-your-first-substrate-chain.md

...of creating new file, via emphasising with `touch` command.

Make commandline to express desired semantic

---

docs/runtime/instantiable-module.md
website/versioned_docs/version-1.0/runtime/instantiable-module.md
website/versioned_sidebars/version-1.0-sidebars.json

This is a follow-up to https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/208 which I accidentally merged before pushing the changes from the second round of feedback.

Joshy instantiable followup

---

website/pages/en/community.js

Adds a description of Substrate Collaborative Learning to the Community page, and provides a few relevant links.

Add Substrate Collaborative Learning to Community page.

---

website/versioned_docs/version-1.0/contracts/cargo-contract.md
website/versioned_docs/version-1.0/contracts/deploying-a-contract.md
website/versioned_docs/version-1.0/contracts/faq.md
website/versioned_docs/version-1.0/contracts/installing-ink.md
website/versioned_docs/version-1.0/contracts/testing-your-contract.md

- Update Ink instructions in V1.0 section.

Update contracts docs for V1.0

---

docs/overview/low-level-data-format.md
docs/runtime/runtime-metadata.md
website/sidebars.json

Fix https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/34
This page targets at the blockchain developers that are not familiar with metadata in the context of Substrate. From this page, users can learn:
* What stores in the metadata, and the difference with other SRML.
* How to interact with the provided rpc method for runtime metadata.
A better reading format locates here: https://hackmd.io/@2dHpJQYgQrCqfxqXMtJTFQ/HJKGguGBS

Init runtime metadata documentation

---

docs/contracts/deploying-a-contract.md
docs/contracts/testing-your-contract.md
docs/tutorials/creating-your-first-contract.md

add +nightly option to cargo test and add the abi-gen info.
update the flipper example to use most recent env type.

update contract create and deploy docs

---

website/static/js/datalayer.js
website/static/js/load.js

Many thanks for the help from @axelchalon

Fix google analytics

---

website/core/Footer.js

Increase Blast `z-index`

---

website/core/Footer.js
website/siteConfig.js
website/static/css/custom.css

Still issues:
* TOC Nav
And when you click one of the nav option you don't land in the right spot.

Temp fix for small screen

---

docs/tutorials/creating-your-first-substrate-chain/front-end.md
docs/tutorials/creating-your-first-substrate-chain/interact.md

Replace double quote with single quotes in JS for PoE tutorial

---

website/core/Footer.js
website/siteConfig.js
website/static/css/custom.css

fixes #273.
Also reverts moving the css out of the component into the css file, because that cements it into the project and makes it not possible to disable the blast anymore. And considering how all over the place mess this is, I would rather contain alll changes at one place to make it easier to remove then put mix them into the custom.css.

Fix menu only on responsive min-width 1024

---

docs/overview/off-chain-workers.md
website/versioned_docs/version-1.0/overview/off-chain-workers.md

Updated the list of APIs for off-chain workers based on recent changes in the code.

Updated Offchain APIs list

---

docs/conceptual/core/executor.md
docs/tutorials/start-a-private-network-with-substrate.md

Here is a doc on the Substrate Executor which goes into details about Wasm and Native Runtime, and ultimately finishes with Runtime Upgrades.

Conceptual Doc: Executor

---

website/siteConfig.js

Increase visibility of Recipes

Remove Reference Docs, Add Recipes

---

website/pages/en/index.js

* Reduces padding on hero section
* Changes the call to actions to become "who" page:
* Contract
* Runtime
* Front-end
* Updates getting started link to the "substrate install" page

Update Home Page

---

docs/conceptual/runtime/primitives.md

Closes https://github.com/paritytech/devex-planning/issues/12

Conceptual Docs: Runtime Primitives

---

website/pages/en/seminar.js

"every other tuesday" -> "every tuesday"

One more cleanup

---

docs/conceptual/runtime/weight.md

Fix https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/348

Fix broken link

---

website/pages/en/seminar.js

Updates Substrate Seminar preparation instructions for 03 Dec 2019.

Substrate Seminar prep instructions for 03 December session.

---

website/core/Footer.js
website/pages/en/videos.js

Add a new footer link for the Substrate Builders program.
(Also fixes small warning from react)

Add Substrate Builders Program

---

website/pages/en/seminar.js

Includes the plan and prep instructions for Seminar on Tuesday December 10th 2019

Seminar instructions for 10 Dec

---

website/pages/en/seminar.js

Cancelling seminar for last minute illness

Cancel Seminar 10 Dec

---

website/pages/en/seminar.js

Seminar description for 17 December

---

website/static/css/custom_docs.css
website/static/css/timeline.css

Separate style from docs and non-docs ordered lists, corrections for both

Style chores

---

docs/getting-started.md

Minor correction to Subkey installation instructions.

Minor fix: subkey installation instructions

---

docs/conceptual/node/extrinsics.md

Add a page documenting extrinsics.
Closes https://github.com/paritytech/devex-planning/issues/8

Add Extrinsics Page

---

docs/tutorials/adding-a-module-to-your-runtime.md

Fixes `contracts-rpc-runtime-api` import

Fix pallet-contracts

---

docs/development/deployment/chain-spec.md

This PR adds docs about the chain spec to devhub. It is currently in a rough draft.
Here are some things I'm specifically wondering about
* Have I covered the right topics? Any to add or remove?
* Are there too many or too few examples? Is it appropriate to have commands or code snippets?
* Do you know the answer or a starting point to answering any of my currently-unknown questions?
* Nitpicks and detailed word adjustments are also welcome, but lower priority right now than the bigger picture things I just asked about.

Chain spec doc

---

docs/tutorials/creating-your-first-substrate-chain/build.md
docs/tutorials/creating-your-first-substrate-chain/setup.md

Updates tutorial to the same commit as the node-template.

Update First Chain Tutorial

---

docs/tutorials/creating-your-first-substrate-chain/build.md

Update first chain tutorial to 3e65111

---

docs/ecosystem/subkey.md
website/pages/en/versions.js
website/sidebars.json
website/versioned_docs/version-pre-2.0/contribute/help-translate.md
website/versioned_docs/version-pre-2.0/development/tools/subkey.md
website/versioned_sidebars/version-pre-2.0-sidebars.json

Added help-translate page back & Fixed subkey page broken link

---

website/pages/en/seminar.js

This PR makes several minor updates to the Seminar page:
* Updates youtube links to point to Parity's playlist rather than my own (at Zach's request)
* Includes last week's recording at the bottom of the page
* Includes upcoming topics in the FAQ

Update seminar page

---

docs/tutorials/creating-a-runtime-module.md
website/pages/en/tutorials.js
website/versioned_docs/version-pre-2.0/tutorials/creating-a-runtime-module.md

Update tutorial to use pallet-template

---

website/versioned_docs/version-pre-2.0/tutorials/creating-a-runtime-module.md

Takes the changes from 417 and copies them back to the pre-2.0 version

duplicate changes from next to pre-2.0

---

website/sidebars.json
website/versioned_docs/version-pre-2.0/tutorials/substrate-front-end/index.md
website/versioned_sidebars/version-pre-2.0-sidebars.json

Sidebar for Front End Tutorial has disappeared previously. This fix adds them back.

Fix front-end tutorial sidebar

---

docs/development/module/fees.md
website/versioned_docs/version-pre-2.0/conceptual/runtime/weight.md
website/versioned_docs/version-pre-2.0/development/module/fees.md

Correct links to recipes

---

website/pages/en/seminar.js

* Links to the most recent recordings
* Posts topics (and potential topics) for the next two weeks
* Fixes spaces vs tabs issue

Update Seminar page for 28 Jan

---

website/pages/en/seminar.js

* Post recording from 28 Jan
* Post February topic schedule

Update Seminar Page (30 Jan)

---

website/pages/en/community.js
website/pages/en/seminar.js

and replace outdated playlist link on community page.

Udate Seminar Page

---

website/pages/en/tutorials.js

Add version tag

---

docs/development/tools/subkey.md

Update subkey docs

---

website/pages/en/seminar.js

Adds latest video, updates upcoming topics.

Joshy seminar 2 mar

---

docs/tutorials/adding-a-module-to-your-runtime.md
website/versioned_docs/version-pre-v2.0-3e65111/tutorials/adding-a-module-to-your-runtime.md

This is my attempt to fix #483.
@riusricardo is this the correct way to link to the tutorials overview page?

Try to fix broken link

---

docs/tutorials/adding-a-module-to-your-runtime.md

Updates to 2.0-alpha.3+
Possible Enhancement:

Update Add a Pallet Tutorial

---

website/pages/en/seminar.js

Post plans for March 10th

---

docs/tutorials/build-a-dapp/prepare.md

Fix the directory name of the installing the dependencies part.

Fix a directory name

---

docs/tutorials/creating-your-first-substrate-chain/setup.md

Add source command in order to load settings.
- Documentation update

Add source command in order to load settings

---

docs/tutorials/adding-a-module-to-your-runtime.md
website/versioned_docs/version-pre-v2.0-3e65111/tutorials/adding-a-module-to-your-runtime.md

Specific versions in add a pallet tutorial.

Set different v2.0 versions

---

website/pages/en/seminar.js

Another standard update of the Seminar page
* Upcoming topics
* Past videos
* Minor revision to FAQ

Update Seminar page (14 Mar)

---

website/pages/en/seminar.js

Adds upcoming topics and recent recording.

Routine Seminar Update

---

docs/tutorials/creating-your-first-substrate-chain.md
website/pages/en/tutorials.js
website/versioned_docs/version-pre-v2.0-3e65111/tutorials/creating-your-first-substrate-chain.md
website/versioned_docs/version-v2.0.0-alpha.3/tutorials/creating-your-first-substrate-chain.md
website/yarn.lock

This PR creates forward pages to redirect users accidentally landing on the v1.0 version of the "Creating Your First Substrate Chain" tutorial.
Additionally, it updates the links in the "Tutorials" pages to use master docs, not `next`.

Redirect "Creating Your First Substrate Chain"

---

website/pages/en/seminar.js

Routine update to the seminar page.
Remove past plans. Post more recordings.

Joshy seminar 27 mar

---

website/pages/en/seminar.js

Adds two most recent recordings and plans for next three weeks.

Routine Seminar page update

---

website/data/users.js
website/static/img/users/encointer.svg

update for substrate project list on substrate.dev

add encointer

---

docs/tutorials/build-a-dapp/pallet.md

Typo, repeated words

---

docs/conceptual/runtime/weight.md
docs/development/module/fees.md

!!! NOTICE !!!
All documentation has been moved to the Knowledge Base. Please make your PR there.
https://github.com/substrate-developer-hub/knowledge-base/

Port substrate-developer-hub/knowledgebase#26

---

website/pages/en/seminar.js

This page replaces the long-outdated seminar page content with the correct current content. This is part of the migrations back to docusaurus.

Update Seminar Page (04 June 2020)

---

website/pages/en/index.js

Fixes the "Get Started" link at the bottom of the landing page.

Fix "Get Started" Link

---

website/siteConfig.js

Temporarily disable search while we find the best solution. There are some concerns related to using Algolia search engine.

Disable search

---

docs/tutorials/build-a-dapp/pallet.md

Add details about pwd when building node template

---

docs/tutorials/start-a-private-network/customchain.md

Closes substrate-developer-hub/tutorials#21
cc: @brenzi, @DemiMarie-parity

Include a CLI option to insert an author's key

---

docs/knowledgebase/advanced/codec.md

Followup to #570. This PR just runs prettier.
Approving reviewer can merge this one.

Run prettier on codec page

---

docs/knowledgebase/runtime/frame.md
docs/knowledgebase/smart-contracts/faq.md
docs/knowledgebase/smart-contracts/ink-development.md

Closes https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/566

Update Knowledge Base FRAME Documentation

---

docs/knowledgebase/getting-started/glossary.md
website/pages/en/seminar.js

This PR removes outdated seminar topics, and adds Cumulus as the topic for the seminar of 23 June

Post seminar topic for 23 June

---

website/pages/en/seminar.js

@JoshOrndorff  I see. You have the seminar description text ready in the calendar. I pretty much just copy and paste :)
Thanks for the advanced preparation.

Seminar Update of 200721

---

website/pages/en/seminar.js

@wheresaddie saw your comment, and added host info.
Also updated seminar info to Jul 28.

Seminar Update

---

website/core/Footer.js
website/pages/en/terms.js

- add and format Terms of Use provided by comms/legal
- add link in footer to Terms of Use
- update date on Terms of Use page

Add Terms of Use

---

website/pages/en/seminar.js

Update seminar July 28

---

website/pages/en/seminar.js

@danforbes This PR is to update the Seminar info. Could you fill out the detail of what Aug 4 Seminar is about? Thanks.

Update of Seminar page

---

docs/tutorials/start-a-private-network/customchain.md

Enhanced finalization docs for private network tut

---

docs/tutorials/visualize-node-metrics.md

Add setup step for installing dependencies

---

docs/knowledgebase/runtime/macros.md

Updates to Runtime Macros Article

---

docs/tutorials/start-a-private-network/customspec.md

Update Private Network Tutorial Chain Spec for v2.0.0-rc6

---

website/pages/en/tutorials.js
website/static/tutorials/substrate-contracts-workshop/index.html

Close #635 
Also refactor the code in `/website/pages/en/tutorials.js`.

Local smart-contracts-workshop tutorial page redirecting to github URL

---

website/sidebars.json

Fix KB Contracts Section Order

---

docs/knowledgebase/integrate/subkey.md
docs/knowledgebase/runtime/off-chain-workers.md
docs/tutorials/start-a-private-network/keygen.md

Subkey Updates for v2.0.0-rc6

---

docs/knowledgebase/getting-started/glossary.md

Reviewing existing definitions from letters `A` through `D`. Add a number of new definitions.

Update Glossary, pt. 1

---

docs/tutorials/add-a-pallet/index.md
docs/tutorials/build-a-dapp/prepare.md
docs/tutorials/create-a-pallet.md
docs/tutorials/create-your-first-substrate-chain/setup.md
docs/tutorials/start-a-private-network/index.md

Backport substrate-developer-hub/substrate-node-template#81

Update to Node Template v2.0.0-rc6+1

---

docs/knowledgebase/getting-started/glossary.md

Update Glossary, pt. 2

---

docs/tutorials/start-a-private-network/customchain.md

Fixed typo customchain.md

---

docs/tutorials/add-a-pallet/configure-a-pallet.md
docs/tutorials/add-a-pallet/import-a-pallet.md
docs/tutorials/add-a-pallet/index.md
docs/tutorials/add-a-pallet/use-a-pallet.md
docs/tutorials/build-a-dapp/front-end.md
docs/tutorials/build-a-dapp/pallet.md
docs/tutorials/build-a-dapp/prepare.md
docs/tutorials/create-a-pallet.md
docs/tutorials/create-your-first-substrate-chain/interact.md
docs/tutorials/create-your-first-substrate-chain/setup.md
docs/tutorials/start-a-private-network/alicebob.md
docs/tutorials/start-a-private-network/customchain.md
docs/tutorials/start-a-private-network/customspec.md
docs/tutorials/start-a-private-network/index.md
docs/tutorials/start-a-private-network/keygen.md
docs/tutorials/upgrade-a-chain/index.md
docs/tutorials/upgrade-a-chain/scheduled-upgrade.md
docs/tutorials/upgrade-a-chain/sudo-upgrade.md
website/pages/en/tutorials.js

Smart contract tutorials not yet updated.

Update most tutorials to v2.0.0

---

website/pages/en/index.js
website/static/css/custom.css

Added a sub0 announcement bar to the top of index page.  
[Screenshots](https://www.notion.so/paritytechnologies/Sub0-Announcement-on-Substrate-io-and-Substrate-dev-39248df8bade496cb671daa180b8fae9)

Adding sub0 announcement as a top bar

---

docs/knowledgebase/runtime/randomness.md

Remove unnecessary bullet.

---

website/pages/en/seminar.js

Seminar page update to include Oct 6, 13, and 20

Seminar page update to include Oct 6, 13, and 20

---

website/pages/en/seminar.js

Changing **Oct** to **October**

Changing "Oct" to "October", just to be consistent 😅

---

docs/knowledgebase/integrate/libraries.md

Add SubstrateNetApi

---

docs/knowledgebase/getting-started/index.md

Depends on https://github.com/substrate-developer-hub/substrate-node-template/pull/92

Add more docs about working with Rust nightlies

---

docs/tutorials/add-a-pallet/import-a-pallet.md
docs/tutorials/add-a-pallet/use-a-pallet.md
docs/tutorials/add-contracts-pallet.md
docs/tutorials/build-a-dapp/pallet.md
docs/tutorials/start-a-private-network/alicebob.md
docs/tutorials/start-a-private-network/customchain.md
docs/tutorials/start-a-private-network/customspec.md

Add some details for Cargo files and use release

Add details and fixes

---

docs/tutorials/create-your-first-substrate-chain/interact.md

edit 'launch it be' from 'be' to 'by'

minor miswording

---

docs/knowledgebase/advanced/executor.md

Based on this https://substrate.dev/rustdocs/v2.0.0/sp_state_machine/enum.ExecutionStrategy.html
I *guessed* at the defaults for runtime. 🤞🏼

Update ExecutionStrategy info

---

website/pages/en/seminar.js

Seminar Page Update.
Whoever approves this PR, please also click the **Merge** button. Thanks!

Seminar Page Update

---

docs/tutorials/add-contracts-pallet.md

closes https://github.com/paritytech/subport/issues/41

fix testnet_genesis

---

docs/knowledgebase/runtime/debugging.md

Closes #696
Related to https://github.com/substrate-developer-hub/recipes/pull/391

Updates to Runtime Debugging Docs

---

docs/knowledgebase/runtime/errors.md
website/sidebars.json

Docs on Runtime Errors

---

docs/knowledgebase/runtime/tests.md

Update Docs for Runtime Testing

---

docs/knowledgebase/getting-started/index.md

The changes I promised [here](https://github.com/substrate-developer-hub/substrate-node-template/pull/99#issuecomment-714308392).
It sure needs some editing. Not a native speaker.
@danforbes @wheresaddie

Rework how the toolchains are explained

---

docs/knowledgebase/getting-started/index.md

fix https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/741

docs to use nix shell

---

website/pages/en/seminar.js

This PR removes two outdated topics from the seminar page, and adds some details to the description of the upcoming Moonbeam presentation.
cc @jimmychu0807

Update seminar page for Moonbeam presentation 27 October

---

website/pages/en/index.js

Fix docs link on homepage

---

docs/knowledgebase/advanced/executor.md
docs/knowledgebase/runtime/execution.md
docs/knowledgebase/runtime/upgrades.md
website/sidebars.json

Runtime Upgrades & Storage Migrations

---

docs/tutorials/start-a-private-network/alicebob.md

Increment Bob's port number to avoid collision with Alice's.

Fix Bob's WebSocket port number

---

docs/tutorials/create-a-pallet.md

Update to avoid confusion with code snippet.

Fix mentioning of default-features

---

docs/tutorials/add-contracts-pallet.md

Highlights the necessary underscore removal.

Highlight necessary change

---

website/pages/en/index.js

Per Ivana, turned on the announcement bar for Polkadot Decoded with the Registration Link.

Turned on the announcement bar for Polkador Decoded

---

docs/knowledgebase/runtime/randomness.md

on-chain randomness: fix link to randomness recipe

---

docs/knowledgebase/runtime/storage.md

I have replaced the broken link with four links pointing to different recipes related to storage.

update broken link to receipe: storage-api

---

docs/knowledgebase/getting-started/index.md
docs/tutorials/add-a-pallet/import-a-pallet.md
docs/tutorials/add-a-pallet/use-a-pallet.md
docs/tutorials/add-contracts-pallet.md
docs/tutorials/build-a-dapp/pallet.md
docs/tutorials/build-permission-network/launch-network.md
docs/tutorials/create-a-pallet.md
docs/tutorials/create-your-first-substrate-chain/setup.md
docs/tutorials/upgrade-a-chain/scheduled-upgrade.md
docs/tutorials/upgrade-a-chain/sudo-upgrade.md

Depends on https://github.com/substrate-developer-hub/substrate-node-template/pull/105

Updates to installation guide

---

docs/knowledgebase/runtime/storage.md

Update storage.md by fixing typo

---

docs/tutorials/add-contracts-pallet.md

Syntax error: seems that the author accidentally cut off the sentence too short.
- [n/a] Are the audience and objective of the document clear? E.g. a document for developers that should teach them about transaction fees.
- [n/a] If this is a new page, does the PR include the appropriate infrastructure, e.g. adding the page to a sidebar?
- [n/a] Do links go to rustdocs or devhub articles rather than code?
- [n/a] If this PR addresses an issue in the queue, have you referenced it in the description?

Minor syntax fix :wrench:

---

readme.md
translation.md

Docs update with instruction to deploy to staging and about translation.
@riusricardo I have update the credential issues in circleCI, and should have fixed the deployment.
@danforbes, @folsen Ricardo, do you have admin access to this repo, and grant me admin for a week to further fix the CI to Heroku deployment? If not, whom should I check with? Thanks.

Minor docs update

---

website/pages/en/seminar.js

Updated seminar for 201208

---

docs/knowledgebase/learn-substrate/off-chain-indexing.md
website/sidebars.json

A short write-up on off-chain indexing. Please expand as desired :)

Off-chain indexing.

---

website/pages/en/terms.js

Parity Technologies has a new address in London.  Updated changes per Legal.

Updated Terms of Use per Legal

---

website/pages/en/seminar.js

Jimmy, just want to make sure I didn't screw up anything w/ the translation stuff.

Update for holiday hiatus

---

website/pages/en/seminar.js

Updates for Seminar

---

docs/knowledgebase/runtime/frame.md

#818 Updating pallet source links to v2.0.0

---

website/pages/en/seminar.js

@jimmychu0807 please do not merge until we get approval from @dastanbeksamatov.
cc @EmilyOstbo

Add 26 Jan Seminar

---

website/pages/en/index.js

Activating the announcement bar for Polkadot Decoded 2021, per Marcomms request.

Adding Decoded 2021 Announcement with a link to submit proposals

---

docs/tutorials/build-permission-network/add-node-authorization-pallet.md

- Add detail and snipped code examples
- 100 chars or less per line
- removed deprecated link
- use `make` build flow

Update permission network style, content polish

---

docs/tutorials/visualize-node-metrics.md

The tutorial here got me stuck at installing and configuring grafana. 
I have updated the content to help make it flow better. :)
I have an updated template I will add in a subsequent commit to this PR

Major update to visualization tutorial

---

docs/tutorials/build-permission-network/launch-network.md

So this gets cleaned up automatically on restart, instead of cluttering user's home folder 🍑

use /tmp folder, not ~/tmp

---

website/pages/en/seminar.js

Add 2 Feb Seminar

---

docs/tutorials/add-a-pallet/use-a-pallet.md

I was confused at this point in the instructions, and tried the "unsigned" and "sudo" buttons and getting various errors before working out I needed to press "signed"

make it clear which button to use when setting names

---

docs/knowledgebase/getting-started/index.md
docs/knowledgebase/smart-contracts/overview.md

Fixing issue mentioned in PR #832

Remove (SEAL) in smart-contracts/overview

---

docs/tutorials/add-contracts-pallet.md

not a big deal, but took me a few minutes to work this out from the error message

clarify this line is an update rather than an addition

---

docs/knowledgebase/integrate/libraries.md

We moved our API to the organization, to allow better maintenance from our team, please updated the entry.

updated to our api library, moved to organisation.

---

docs/knowledgebase/integrate/subkey.md
docs/tutorials/start-a-private-network/keygen.md

This will resolve the compilation issues people are running into with subkey https://github.com/paritytech/substrate/issues/8131

add --locked to cargo install instructions to avoid deps issues

---

docs/knowledgebase/advanced/storage.md

Creating this PR over #864 to kick off the CI process
Close #864

Fix missing quotes in storage.md

---

website/core/Footer.js

changing twitter handle to substrate instead of parity.io in footer (per marcomms)

Updating Twitter Handle

---

docs/index.md

Minor modifications to improve readability.

Proof-reading :eyes:

---

docs/tutorials/add-contracts-pallet.md
website/pages/en/tutorials.js

2nd pass Update add contracts v3

---

docs/knowledgebase/runtime/execution.md

added on idle docs

---

docs/knowledgebase/getting-started/index.md
docs/knowledgebase/getting-started/windows-users.md
docs/tutorials/add-a-pallet/index.md
docs/tutorials/build-a-dapp/front-end.md
docs/tutorials/build-a-dapp/index.md
docs/tutorials/build-permission-network/index.md
docs/tutorials/create-your-first-substrate-chain/index.md
docs/tutorials/create-your-first-substrate-chain/interact.md
docs/tutorials/upgrade-a-chain/index.md

Added copy to help with common missteps and errors.
- M1 macs
- windows native -> WSL
- rustup tips
Compliments #881 , but not required for it

Install guide update with tips and tricks added

---

docs/tutorials/create-your-first-substrate-chain/background.md
docs/tutorials/create-your-first-substrate-chain/setup.md
website/pages/en/tutorials.js

- fix #911 CI links 
- Bump v3 for all cards 
- card images and sorting updated

update links, bump version numbers to v3 in tuto cards

---

docs/knowledgebase/runtime/benchmarking.md
website/pages/en/tutorials.js

@NukeManDan 
Hiding empty benchmarking tut

Hiding benchmarking tut

---

docs/tutorials/start-a-private-network/customspec.md

Grammar correction

---

docs/tutorials/build-permission-network/add-node-authorization-pallet.md
docs/tutorials/build-permission-network/index.md
docs/tutorials/build-permission-network/launch-network.md

Update permissioned network tutorial to v3

---

docs/knowledgebase/getting-started/glossary.md

fixed some links in the glossary :)

fixed anchors

---

docs/knowledgebase/runtime/metadata.md

Code for fetching metadata is updated based on: https://github.com/polkadot-js/api/issues/3338#issuecomment-803273632

Close #916

---

website/sidebars.json

@riusricardo @NukeManDan 
This page seems relevant. Do you have the context why this page is removed from the sidebar?

Shows contracts pallet page on sidebar

---

docs/knowledgebase/getting-started/index.md

grantee -> guarantee
specify -> specific
dropped "if" from sentence but I think it still reads slightly improperly

Fix additional typos and grammar issues

---

docs/knowledgebase/getting-started/index.md

Fix typo: computre -> computer

---

docs/tutorials/start-a-private-network/keygen.md

fix: fixing of typo

---

docs/tutorials/build-permission-network/add-node-authorization-pallet.md
docs/tutorials/build-permission-network/index.md
docs/tutorials/build-permission-network/launch-network.md

- formatting, add notes, grammar check
- bump bs58 -> 0.4.0 in docs
- new v3 [solution added](https://github.com/substrate-developer-hub/substrate-node-template/tree/tutorials/solutions/permissioned-network-v3)

Permissioned update

---

docs/knowledgebase/getting-started/index.md
readme.md

Fix minor typos

---

docs/tutorials/start-a-private-network/customchain.md

fix: small typo ;-)

---

.well-known/security.txt
website/pages/en/index.js
website/static/.well-known/security.txt

Activating Polkadot Decoded ad 
+ Adding security files as directed by Security Team.

Security file update

---

docs/tutorials/add-a-pallet/import-a-pallet.md

use "text" language identifier

---

website/pages/en/index.js

Disabling polkadot decoded voting ad temporarily,  until the registration page is live.

disabling Polkadot Decoded Vote ad

---

docs/tutorials/add-contracts-pallet.md

builder was not able to find where to make the change

clarify code block addition gatcha

---

docs/knowledgebase/advanced/executor.md

Close #963
@NukeManDan please review. Thanks

Added the cli argument to actual execution strategy name mapping

---

docs/tutorials/create-your-first-substrate-chain/interact.md

typo correction

---

docs/tutorials/create-your-first-substrate-chain/interact.md

see https://stackoverflow.com/a/67074963/68115

added a hint on how to stop the node

---

docs/knowledgebase/getting-started/index.md

the following command / package mappings from the apt (ubuntu/debian) instructions were used:
* `sudo apt update` -> `sudo dnf update`
* `sudo apt install` -> `sudo dnf install`
* `cmake` -> `cmake`
* `pkg-config` -> `pkgconf-pkg-config`
* `libssl-dev` -> `openssl-devel`
* `git` -> `git`
* `build-essential` -> `make automake gcc gcc-c++ kernel-devel` (see: https://unix.stackexchange.com/a/1344/39654)
* `clang` -> `clang`
* `libclang-dev` -> `clang-devel`
* `curl` -> `curl`
* `libz-dev` -> `zlib-devel`

Add fedora and update other linux packages dependencies for substrate & the FE template

---

docs/tutorials/create-a-pallet.md

typo fixes

---

docs/knowledgebase/runtime/metadata.md

Update 'event' to 'events' in metadata note

---

docs/tutorials/build-a-dapp/prepare.md

Update "controler" to "controller"

---

website/pages/en/index.js

Activating Polkadot Decoded Banner.

Decoded register banner

---

docs/knowledgebase/getting-started/index.md

Adding instructions about environment dependencies for Debian and OpenSUSE which install ``llvm-config`` and ``clang``.

Updating requirements

---

docs/tutorials/add-a-pallet/configure-a-pallet.md

Fix comment typo from "Ballances" to "Balances"

---

docs/tutorials/build-a-dapp/front-end.md
docs/tutorials/build-a-dapp/pallet.md
docs/tutorials/build-a-dapp/prepare.md

edits for clarity & solutions

---

docs/tutorials/build-a-dapp/front-end.md
docs/tutorials/build-a-dapp/index.md
docs/tutorials/build-a-dapp/pallet.md
docs/tutorials/build-a-dapp/prepare.md

This updates the "build a dapp" / PoE tutorial to FRAME v2. 
@NukeManDan @jimmychu0807 please double check on your end. Works on mine but ... verify first ;)
This will be followed by updating the solutions branch in the node-template repository.

Update PoE tutorial to FRAME v2

---

docs/knowledgebase/learn-substrate/off-chain-features.md

Companion PR to: https://github.com/substrate-developer-hub/recipes/pull/435. Merge this only after the recipes PR is merged.

Updated with off-chain indexing example

---

website/pages/en/seminar.js

Adding dates for June 1, 15 and 29.

Update seminar schedule 

---

docs/knowledgebase/advanced/ss58-address-format.md
website/package.json
website/pages/en/newsletter.js
website/yarn.lock

@NukeManDan 
Close: #1007
Clear a warning that `charset` is not proper key

Fixing missing links

---

docs/knowledgebase/runtime/metadata.md

Minor fix.

---

website/pages/en/index.js

Disabling Decoded Banner

---

docs/tutorials/add-a-pallet/configure-a-pallet.md
docs/tutorials/add-a-pallet/import-a-pallet.md
docs/tutorials/add-a-pallet/index.md
docs/tutorials/add-a-pallet/interact-with-a-pallet.md
website/sidebars.json

This is the corresponding [Substrate node template solution](https://github.com/substrate-developer-hub/substrate-node-template/tree/tutorials/solutions/add-a-pallet-v3.0.0%2Bmonthly-2021-05).

Updated add-a-pallet to `v3.0.0+monthly-2021-05`

---

docs/knowledgebase/integrate/memory-profiling.md

I've rewritten and updated the docs related to memory profiling, expanding them slightly and aligning them to the newest version of the profiler.

Update the memory profiling documentation

---

website/static/js/load.js

Updating Simple Analytics script link.

Updated simple analytics tracking link

---

docs/knowledgebase/learn-substrate/session-keys.md

Changed broadcast to broadcasting

---

docs/knowledgebase/learn-substrate/weight.md

Made changes to the Transaction weight definition

---

docs/knowledgebase/learn-substrate/tx-pool.md

I made one or two changes to a sentence, mostly grammatical, to make the explanation clearer

---

docs/knowledgebase/getting-started/index.md

closes #867
(closes for now at least 🙏🏼 )
looks like recent monthly builds solve this! Included a note.

update m1 suppport

---

docs/tutorials/create-your-first-substrate-chain/setup.md

Cloning the proper `v3.0.0+monthly-2021-05` branch as we do in the next tutorial [here](https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/blob/source/docs/tutorials/add-a-pallet/index.md).
BTW, why don't we use `master` here?

[setup] Updating git branch

---

docs/tutorials/add-a-pallet/import-a-pallet.md

A small typo I ran into while following the tutorial.

Typo in Nicks Pallet tutorial

---

docs/knowledgebase/learn-substrate/weight.md
docs/knowledgebase/runtime/benchmarking.md
docs/knowledgebase/runtime/fees.md
website/sidebars.json

- With title enhancement
- Close #946

Linking from transaction fee to benchmarking page

---

docs/tutorials/add-contracts-pallet.md

Fixed few compilation errors and deprecations that I ran into while following Add Contracts Pallet tutorial (probably caused by recent updates).
Also pinned dependencies to `monthly-2021-05` tag to be consistent with the first tutorial that sets up new users (i.e. [Set Up Your Computer](https://substrate.dev/docs/en/tutorials/create-your-first-substrate-chain/setup)), so people following along the "Next Steps" suggestions can build on top of previous tutorials.

Add Contracts Pallet tutorial: Updates / fixes and pin to tag monthly-2021-05

---

docs/knowledgebase/smart-contracts/evm-pallet.md

Correct typo

---

docs/tutorials/add-contracts-pallet.md
docs/tutorials/build-permission-network/index.md

Continuation of 
https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/1055
but using the source branch!

Example uses const on a non-const fn 2

---

docs/knowledgebase/runtime/metadata.md

making snippet running with node.js as well!

---

website/pages/en/index.js

Adding Sub0 Proposal Banner

---

website/data/past-seminars.json
website/pages/en/seminar.js

Includes past and upcoming Seminars.

Update seminar pages

---

website/data/past-seminars.json
website/pages/en/seminar.js

- Adds August 10 and 24.
- Fixes </code> tag for July 27 entry

Update seminar page ✨ 

---

docs/tutorials/add-a-pallet/configure-a-pallet.md

use FRAME V2 macros to match Nicks version

---

website/core/Footer.js
website/data/custom-translation-strings.json

Adds Playground and How-to guide links in footer.

Add footer links 

---

docs/knowledgebase/runtime/pallets.md

missing type in storage config

---

docs/knowledgebase/getting-started/glossary.md
docs/knowledgebase/integrate/subkey.md
docs/knowledgebase/runtime/frame.md
docs/knowledgebase/runtime/randomness.md
docs/knowledgebase/smart-contracts/index.md
docs/tutorials/add-contracts-pallet.md
docs/tutorials/visualize-node-metrics.md

Someone kindly pointed out that it didn't compile, so I've worked through the tutorial and updated it.

Updated tutorial so compiles with monthly-2021-08 tag

---

docs/knowledgebase/runtime/benchmarking.md

minor grammatical corrections

---

docs/tutorials/build-a-dapp/pallet.md

- [] If this PR addresses an issue in the queue, have you referenced it in the description?

replace deprecated Module with Pallet

---

docs/tutorials/create-your-first-substrate-chain/interact.md

[docs] fixed sudo link

---

docs/tutorials/add-a-pallet/configure-a-pallet.md
docs/tutorials/add-a-pallet/import-a-pallet.md

Correcting incorrect parameter type.

Update `nicks-pallet` parameter types for nicks pallet ver4.0

---

docs/knowledgebase/integrate/try-runtime.md

Fix on #1111
Thanks @JoshOrndorff for reporting this.

Close #1111

---

website/pages/en/index.js

Activating Banner for Sub0 - 2021

Registration Banner for Sub0

---

docs/knowledgebase/integrate/try-runtime.md

Close #1119.
- Add `follow-chain` to CLI options
- Add examples from source code docs

Update try-runtime docs

---

docs/tutorials/add-contracts-pallet.md

patch for #1128 - cherry picked from @sacha-l 's commit I mangled :sweat_smile:

framev2 and formatting

---

website/pages/en/index.js
website/static/css/custom.css

Banner style updates to make it more prominent per Marcomms.

banner style updates

---

docs/tutorials/build-permission-network/add-node-authorization-pallet.md

+ broken link and a misprint correction
+ fixes in code lines to solve _node-template_ compilation errors

Fixes proposed to Permissioned Network tutorial

---

docs/tutorials/frontier/index.md

misprints in code blocks fixed for handy use with copy\paste

Patch to Frontier tutorial

---

docs/tutorials/add-a-pallet/import-a-pallet.md

when using the tag tag = 'monthly-2021-09+1' I get an error hence the update to the same tag as all other depencies

fix tag on dependency

---

docs/tutorials/visualize-node-metrics.md

a tiny fix for Node Metrics Tutorial

---

website/pages/en/index.js
website/static/css/custom.css

New Substrate Documentation Announcement bar with Sub0 Registration. 
@sacha-l 
Merge whenever ready! 
Label - `do-not-merge` is just so nobody else merges this, you can ignore and merge whenever ready!

new substrate documentation announcement
