substrate-developer-hub/substrate-developer-hub.github.io

style-guide.md
Addresses https://github.com/paritytech/substrate-developer-hub/issues/59
The goal of this style guide is to make our documentation more readable by having consistent grammar and usage across our docs.
For example, readers should not see `my_macro` and `my_macro!` depending on who wrote that particular page.
=> Create style guide for documentation

.circleci/config.yml
Issue [link](https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/84#issuecomment-499744642)
* I have manually published to my own [website](https://whisperd.tech/substrate-developer-hub.github.io/), the images for `Who is Building on Substrate?` is lost, because I add `baseUrl: '/substrate-developer-hub.github.io/'` in my publishment.  It should work under substrate.dev.
* The circleci build needs to hold two environment variables `CROWDIN_DOCUSAURUS_PROJECT_ID`, `CROWDIN_DOCUSAURUS_API_KEY`, need to figure out how to configure the value in circleci.
=> Download translation, and upload source docs in CI.

docs/tutorials/adding-a-module-to-your-runtime.md
Current command
```
curl https://getsubstrate.io -sSf | bash -- -s --fast
```
yields the following error on my MacOS
```
bash: -s: No such file or directory
(23) Failed writing body
```
=> Fix the command to install the prerequisites

.circleci/config.yml
So that approved translations can be deployed.
=> Schedule deploy at utc midnight.

docs/tutorials/creating-a-runtime-module.md, website/versioned_docs/version-1.0.0/tutorials/creating-a-runtime-module.md
As requested by @bkchr, This PR emphasizes `default_features = false` to help readers familiar with rust, but not substrate avoid reading over the advice by accident.
=> Emphasize default_features = false

docs/overview/off-chain-workers.md, website/versioned_docs/version-1.0.0/overview/off-chain-workers.md
When the offchain workers article was added to devhub we did not yet have versioning enabled. Now that https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/157 is merged we do have versioning.
This PR removes the offchain workers article from the 1.0 devhub because offchain workers are not available in 1.0 It leaves a link to the newer docs so that the excellent writeup is still discoverable by someone browsing the 1.0 docs.
As an aside it changes the article's title from
```diff
- Substrate Off-Chain Workers
+ Off-Chain Workers
```
since everything here is about Substrate.
=> Add versioning to offchain workers article

docs/runtime/initializing-storage.md, docs/runtime/macros/decl_module.md, website/versioned_docs/version-1.0.0/runtime/initializing-storage.md, website/versioned_docs/version-1.0.0/runtime/macros/decl_module.md
Fix `marco` typo.
Clarify that using `config()` is not mandatory to use default storage value.
=> Fix typo and clarify default value usage

docs/contracts/index.md
Three minor fixes:
* Substrate Module Runtime Library -> Substrate Runtime Module Library
* revertable -> revertible ([ngram](https://books.google.com/ngrams/graph?content=revertible%2Crevertable&year_start=1800&year_end=2000&corpus=15&smoothing=3&share=&direct_url=t1%3B%2Crevertible%3B%2Cc0%3B.t1%3B%2Crevertable%3B%2Cc0))
* executed completes -> execution completes
=> Fix minor typos in contracts overview.

docs/runtime/instantiable-module.md, website/sidebars.json
Questions to consider
* Should we make a module template that is _already_ instantiable? maybe as part of https://github.com/shawntabrizi/substrate-module-template
* Should I show the code snippets as diffs instead of just the new code. Diffs are more clear for those who know how to read them, but may distract newer developers.
* Should I add paragraph text before each of the snippets? It felt weird stylistically to have sections that were nothing but short code snippets, but I couldn't think of anything to write there that wasn't just filler text.
* About the video
* Anyone know how to make it start at the start?! For me it always starts like 17 mins in?
* Apps UI didn't properly support modules at the time of recording. It does now. I think it's worth keeping the recording, but I can …
=> Instantiable Modules

website/pages/en/index.js, website/pages/en/users.js
@Kholostenko suggested we open the website for the different Substrate users in a new tab, hopefully keeping them on substrate.dev longer even if they start clicking away.
=> Open "users" on a new tab

.circleci/config.yml
In https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/222 we agreed that no PRs should be merged into `source` unless the build passes in CI. This PR enables a job which checks the build. Once this goes in, I can require that the build pass in github settings and we can close the issue.
=> Update CI config to check each build

docs/runtime/architecture-of-a-runtime.md, docs/tutorials/start-a-private-network-with-substrate.md, website/versioned_docs/version-1.0/tutorials/start-a-private-network-with-substrate.md
Clarifies language about exactly which options validators joining a testnet should use.
Based on feedback from riot.
=> Joshy clarify testnet

docs/tutorials/substrate-front-end/part-3-transfer-funds.md
Fix typo
`The the status ...` -> `The status ...`
=> Fix repeated word typo in frontend tutorial

docs/tutorials/substrate-front-end/part-1-connect-to-a-node.md
Although react semantic ui is not the focus of this tutorial, I think linking its docs once at the outset is warranted so devs who want to dig deeper don't get confused [like I did](https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/233).
=> Add link to react semantic ui docs

website/pages/en/who/contract-developer.js
When we removed the `contracts` docs, we forgot to clean up the `who` page
=> Fix `who` docs for Contracts

website/core/Footer.js
@gnunicorn @kaichaosun 
This is a temporary fix to remove the one CSS item breaking Klaro stuff. @gnunicorn will follow up to make a real fix so his feature still works.
=> Remove body transform

docs/getting-started.md
Only thing missing here is "Next Steps" items, which we can add when we do final pass of the "next" documentation.
Uses _no_ scripts... although we might want to consider including the `getsubstrate.io` script since it is really nice for Mac/Linux users.
=> Add `getting-started` docs to `next`

docs/development/module/macros.md, docs/development/module/storage.md, docs/tutorials/adding-a-module-to-your-runtime.md
Update in two files under `module` are trivial.
Today I walked through adding-a-module-to-runtime tutorial. Some codes doesn't compile, and some are not so clear. So the tutorial is also updated.
=> Updated adding-a-module-to-runtime tutorial and minor words update

docs/tutorials/creating-a-runtime-module.md
@JoshOrndorff @shawntabrizi  Feel free to update/modify on top of this branch
Updates mostly consisted of:
- the 1st section `Create your Node` clone from substrate-node-template, instead of `substrate-new-node`
- module template clone from https://github.com/substrate-developer-hub/substrate-module-template, instead of Shawn personal github repo.
- some path update, and the adding description on path relationship between node-template and module-template, and which `Cargo.toml` we are talking about.
- Don't recommend the v1.0 branch
- Added a next step section at the end
=> update `Creating a Runtime Module` tutorial

website/data/users.js
Firefox fails to load some images because of capitalization issues with the image filename.
Does not fail on chrome.
=> Fix capitalization on images

website/versioned_docs/version-1.0/tutorials/creating-your-first-substrate-chain.md
The issues in #306 are about the v1.0 docs which will be deprecated soon. Nonetheless, these were easy fixes to include.
=> Fix minor errors in v1 first chain tutorial. #306

website/core/Footer.js, website/pages/en/community.js, website/pages/en/seminar.js
Adds a landing page for Substrate Seminar. Includes a footer link, and updates the community page.
The landing page is currently quite minimal, and I'm under no illusion that it's complete. For one thing, it needs input from design team. It will also look better after a few recordings have been made and embedded.
Nonetheless, I'd like to merge this version soon and iterate in a followup so that we can tweet the landing page before the session on Monday.
=> Add Substrate Seminar Landing Page

website/versioned_docs/version-1.0/runtime/instantiable-module.md
There was a weird second title section in the versioned instantiable module doc which caused it to render like this
I've simply removed it here.
=> Remove incorrect second title from Instantiable modules in v1.0 docs.

.circleci/config.yml, scripts/deploy-staging, website/siteConfig.js
Staging site deployed at: https://staging.substrate.dev
**Instruction to use**
- Work on your new doc / UI change in your branch. 
- Commit your new change. 
- Run `scripts/deploy-staging`. This generates published pages and push those pages to `staging` branch, which Heroku is configured to pickup and deploy to the site.
- When everything looks good, you can merge/PR your branch to `source`, and deploy to production of substrate doc site.
**Next todo**
- Integrate with translation
=> Adding script and logic for deploying staging site

docs/overview/off-chain-workers.md, website/versioned_docs/version-1.0/overview/off-chain-workers.md
We removed the comparison of off-chain workers with oracles to align it with the messaging. Off-chain workers don't completely replace oracles rather make their integration easier.
=> Updated off-chain workers overview doc

website/sidebars.json
In my recent PR to update the private network tutorial, I failed to add the proper sidebars to the tutorial. This solves that.
We will also need to update the link on from the tutorials index when we launch v2.0
=> Add sidebars for private network tutorial

website/pages/en/community.js, website/pages/en/seminar.js
I learned from @Isaac-DeFrain that the calendar link still showed the old times. Although I'm certain I edited the event, I didn't realize that the link would change. This PR updates to the correct link.
=> Correct Calendar Link

website/core/Footer.js
Fixes a small warning error about `class` vs `className`
=> Fix class warning

website/pages/en/community.js, website/pages/en/seminar.js
This points links to the newly-created Substrate Seminar playlist while squirreling away a pointer to the old SCL playlist so it is still accessible. Both playlists link to each other on youtube.
=> Create new Seminar playlist.

docs/ecosystem/contracts/ink.md, docs/overview/session-keys.md, docs/runtime/macros/construct_runtime.md, docs/runtime/substrate-runtime-module-library.md, docs/tutorials/adding-a-module-to-your-runtime.md, website/versioned_docs/version-1.0/ecosystem/contracts/ink.md, website/versioned_docs/version-1.0/overview/session-keys.md, website/versioned_docs/version-1.0/runtime/macros/construct_runtime.md, website/versioned_docs/version-1.0/runtime/substrate-runtime-module-library.md, website/versioned_docs/version-1.0/tutorials/adding-a-module-to-your-runtime.md, website/versioned_docs/version-1.0/tutorials/creating-your-first-substrate-chain.md
Most of them convert to `rustdocs/v1.0`, one case, I changed to `rustdocs/master/pallet_`
=> Remove crates.parity.io links

docs/tutorials/adding-a-module-to-your-runtime.md
Moves the `cargo run` instruction to the end.
=> Fix order in tutorial

website/pages/en/seminar.js
This PR updates the seminar page to clarify that Substrate Seminar will not meet over the holiday break and will resume January 7th 2020.
=> Cancel's Substrate Seminar during 2019-2020 holiday break

docs/conceptual/core/consensus.md
The images in the consensus writeup were not showing because there needs to be a blank line before images in markdown.
=> Fix consensus images

docs/getting-started.md
The prerequisite install command (for Debian) had `git` listed twice. While harmless, it was confusing and not idiomatic. This removes the second occurrence.
=> Remove duplicated git dependency in install command

docs/conceptual/runtime/weight.md, docs/development/module/events.md, docs/development/module/tests.md
This PR fixes broken links from the devhub to the recipes.
I've also fixed broken links _from_ the recipes in https://github.com/substrate-developer-hub/recipes/pull/126
@jimmychu0807 pointed out the excellent drlinkchecher.com tool for finding broken links.
=> Fix links from docusaurus to recipes

docs/overview/glossary.md
I find myself frequently describing the dev phrase and linking [directly to source](https://github.com/paritytech/substrate/blob/6e0a4877afbe2309e106b84333bb70200531b604/primitives/core/src/crypto.rs#L43). This PR adds a `Dev Phrase` item to the glossary says a sentence about what it is, and then lists the phrase. This will be a discoverable, linkable, and persistent place to document the dev phrase.
=> Add dev phrase to glossary

website/pages/en/tutorials.js
Fixes a redirect issue.
Docusaurus is redirecting to different tutorials if a trailing slash is missing.
https://substrate.dev/docs/en/tutorials/creating-your-first-substrate-chain/
https://substrate.dev/docs/en/tutorials/creating-your-first-substrate-chain
=> Fix tutorial redirect

docs/development/tools/subkey.md, docs/ecosystem/subkey.md, website/versioned_docs/version-1.0/ecosystem/subkey.md, website/versioned_docs/version-pre-2.0/development/tools/subkey.md, website/yarn.lock
Adds our signed binary to subkey install instructions as we are listing Subkey as an option for the public to claim their Polkadot tokens.
Updated yarn so added the lock file changes in a separate commit that we can revert.
Also added new comment tag that I suggest we start using, `RELEASE-TODO`, so we can quickly search for places we will need to update once we release 2.0.
=> Add signed binary to subkey install options

docs/conceptual/runtime/weight.md, docs/development/module/events.md, docs/development/module/fees.md, docs/development/module/tests.md, website/versioned_docs/version-pre-2.0/conceptual/runtime/weight.md, website/versioned_docs/version-pre-2.0/development/module/events.md, website/versioned_docs/version-pre-2.0/development/module/fees.md, website/versioned_docs/version-pre-2.0/development/module/tests.md
This companion PR updates links from Devhub to Recipes to match the new directory structure in https://github.com/substrate-developer-hub/recipes/pull/143
This should not be merged until that one is merged.
=> Companion PR for Recipes restructure

docs/tutorials/creating-your-first-substrate-chain/interact.md, website/versioned_docs/version-pre-v2.0-3e65111/tutorials/creating-your-first-substrate-chain/interact.md
Clarifies instructions for connecting apps to a local node. This likely fixes the ambiguity that led to #451
=> Update Apps link and say connect to local node.

docs/tutorials/visualizing-node-metrics.md
The Grafana JSON endpoint exposed by Substrate is being removed in favor
of a new Prometheus endpoint. This patch updates the docs accordingly.
Do not merge before corresponding Substrate pull request is merged: https://github.com/paritytech/substrate/pull/4511/
=> docs/tutorials/visualizing-node-metrics: Update to Prometheus endpoint

website/versioned_docs/version-pre-v2.0-3e65111/tutorials/build-a-dapp/prepare.md
Now that the front end template has tagged versions, the older version of the PoE dApp tutorial should explicitly reference the correct version of the front end template.
This is sort of a followup to #493
=> Front end template tag

website/pages/en/seminar.js
This PR is not a routine update to the seminar page. Rather, it updates the zoom call and google calendar links to reflect the decision that the seminar community made to _always_ host seminar at 14:00UTC regardless of any particular daylight savings time.
=> Update seminar links

docs/tutorials/build-a-dapp/pallet.md
Explicitly returning DispatchResult implies that one can change the result type of the functions. Rather than mislead the user this way, I propose removing DispatchResult and accompanying `Ok` returns, so that the macro takes care of that part for the user.
=> Remove DispatchResult

docs/conceptual/core/codec.md
This PR aims to document the behavior of the codec when decoding structures.
Indeed, one might expert this test to work:
```rust
#[test]
fn binaryheap_decode_encode_test() {
let mut bytes: &[u8] = &[8, 1, 0, 0, 0, 0, 0, 0, 1];
let expected = bytes.clone();
let obj = <BinaryHeap<u32>>::decode(&mut bytes).unwrap();
let data: &[u8] = &obj.encode();
assert_eq!(expected, data);
}
```
However this doesn't work: indeed when BinaryHeap decodes those bytes, it constructs a valid struct from them, which means that the structure inside of `obj` is actually represented this way `[8, 0, 0, 0, 1, 1, 0, 0, 0]`.
re: @kirushik
=> Add doc explaining behaviour of ordered structures

CONTRIBUTING.md, readme.md
This repository is being deprecated as content is ported to the https://github.com/substrate-developer-hub/substrate-cms repo.
This PR adds notices explaining that to the `README` and `CONTRIBUTING` files.
=> Adds deprication warning

docs/development/module/debugging.md, website/sidebars.json
This PR brings the beginning of an article on runtime debugging into the KB from the recipes. The work was started in substrate-developer-hub/recipes#134 and took a detour at https://github.com/substrate-developer-hub/knowledge-base/pull/9 on its way here.
=> Article on Debugging

docs/tutorials/adding-a-module-to-your-runtime.md, docs/tutorials/build-a-dapp/pallet.md, docs/tutorials/build-a-dapp/prepare.md, docs/tutorials/creating-a-runtime-module.md, docs/tutorials/creating-your-first-substrate-chain/interact.md, docs/tutorials/creating-your-first-substrate-chain/setup.md, docs/tutorials/start-a-private-network/alicebob.md, docs/tutorials/start-a-private-network/customchain.md, docs/tutorials/start-a-private-network/index.md
This PR updates 5 tutorials to `v2.0.0-alpha.5`. I've updated each tutorial in its own commit you reviewers can easily see which tutorials are updated.
Very little has changed API-wise since `alpha.3`, but this is the first time these tutorials take dependencies from crates.io
=> Update tutorials to alpha.5

.github/pull_request_template.md
This PR removes the deprecation notice from the PR template and restores the normal PR checklist. This is part of the migrations back to docusaurus.
=> Restore normal (non-deprecated) PR template

website/core/Footer.js, website/siteConfig.js
The automatic crawler was triggered by Algolia's team.
It should be fine to point again to the old index.
=> Reset API key

website/pages/en/404.js, website/siteConfig.js, website/static/js/redirect-next.js
This adds a small JS script to every page of the developer hub.
We check the current url, and see if any of the desired redirect patterns match.
If so, we take the user to the new page, leaving the old page in history.
This script currently replaces instances of `docs/en/next` or `docs/next` with `docs/en/knolwedgebase` or `docs/knolwedgebase` which should handle the majority situation.
Custom full redirects beyond that can be added given the template I have provided, or this script can be modified for the needs of the site.
=> Custom redirect for broken pages

docs/knowledgebase/runtime/pallets.md
Upon trying to debug some substrate code and looking through the docs, I saw that there was some discrepancies between the [substrate recipes book](https://substrate.dev/recipes/2-appetizers/2-storage-values.html) and this document with regards to declaring getters for storage variables. 
I have amended the example code to be in line with the recipe code.
=> Added `fn` to storage getters.

docs/knowledgebase/getting-started/glossary.md
Closes #582 
Using link that @AlistairStewart specified.
=> Fix links to GRANDPA PDF in GitHub

.circleci/config.yml
This PR replaces the previous linkchecker (blc) with the custom docker image that the [w3f uses](https://github.com/w3f/polkadot-wiki/blob/936ab5a10ee162a4fcb1c20e0b816d3cea11d963/.circleci/config.yml#L15-L42) in the Polkadot wiki.
This is a naive copy paste job just to see if it works. It may give us trouble because of international docs. I noticed they were excluded in the previous linkcheck. Let's just see.
Next attempt if this one also fails:
We could use https://github.com/gaurav-nelson/github-action-markdown-link-check as we do [in the Recipes](https://github.com/substrate-developer-hub/recipes/blob/master/.github/workflows/link-check.yml). It hasn't been perfect, but it has been pretty good and it isn't blocking several PRs from being merged all because of HTTP 429
=> Crib linkchecker from w3f

Dockerfile, docker-compose.yml, website/package.json
@danforbes  @joepetrowski 
With this PR, you can run in the `website` directory: 
- `yarn check-links`: this will build our doc docusaurus website into an image, download the `web3f/link-checker` image (if not existed), and start them in containers to check links. Note that by the end of running link-checker, the docusaurus website will not kill itself, so dev need to terminate it manually with `ctrl-C`.
- `yarn check-links-cleanup`: there will be some docker container traces left in your machine after running the above cmd. Use this cmd to clean them up.
You need to have `docker` and `docker-compose` installed to run these two commands.
Fixes: #592. This unifies link checking locally and in the CI. 
Running result on my machine:
=> Enable running check-links locally with web3f/link-checker

docs/tutorials/build-a-dapp/pallet.md
Remove the system alias and aligns the tutorial to the node-template code.
=> Align POE tutorial with template

docs/tutorials/start-a-private-network/customchain.md
This PR correct a minor mistake to the note about finality that was added in #610.
As a practical counter-example, try running this tutorial and fail to insert Bob's Aura key. You'll find that only Alice authors blocks, but both authorities cast finality votes. Blocks will still be finalized.
=> Minor clarification about finality voting

docs/knowledgebase/integrate/subkey.md
This PR adds details and examples about using `subkey insert`. Specifically it clarifies that the `-e` option is necessary when inserting grandpa ed25519 keys. Reported by @siman
=> Correct and clarify docs about `subkey insert`

website/pages/en/seminar.js
This PR prunes 3 old seminar descriptions and adds one new one to the seminar page.
This should have been done a week ago, but I somehow missed it. Quick review appreciated.
=> Update Seminar topics

website/pages/en/seminar.js
This PR updates the Substrate Seminar page to include the scheduled topics through the month of September.
It also fixes a minor date formatting issue in the bottom of the page.
=> Update seminar page

docs/tutorials/start-a-private-network/customchain.md
The "paramter" typo was corrected, and usage of the `--chain` flag was written different (line 21 and 157). Minor stuff, but it added unnecessary noise to the documentation.
=> Fixed typo and inconsistent guidance

docs/tutorials/create-your-first-substrate-chain/setup.md
We cannot run `yarn start` on v2.0.0-rc6 
ref: https://github.com/substrate-developer-hub/substrate-front-end-template/issues/128#issuecomment-695773889
This issue was already fixed on v2.0.0 so we'd better to update the document guide also!
=> use release version v2.0.0 to avoid yarn start issue

docs/knowledgebase/advanced/block-import.md, docs/knowledgebase/advanced/codec.md, docs/knowledgebase/advanced/consensus.md, docs/knowledgebase/advanced/cryptography.md, docs/knowledgebase/advanced/executor.md, docs/knowledgebase/advanced/storage.md, docs/knowledgebase/integrate/chain-spec.md, docs/knowledgebase/runtime/debugging.md, docs/knowledgebase/runtime/events.md, docs/knowledgebase/runtime/execution.md, docs/knowledgebase/runtime/fees.md, docs/knowledgebase/runtime/frame.md, docs/knowledgebase/runtime/index.md, docs/knowledgebase/runtime/macros.md, docs/knowledgebase/runtime/origin.md, docs/knowledgebase/runtime/tests.md, docs/knowledgebase/smart-contracts/contracts-pallet.md, docs/knowledgebase/smart-contracts/overview.md
Use `./scripts/update-kb-rustdocs` to update.
=> Update Rustdocs links

docs/knowledgebase/runtime/storage.md
Links to StorageValue, StorageMap and StorageDoubleMap were broken.
=> Fix broken links

docs/tutorials/build-a-dapp/front-end.md
Hopefully fix substrate-developer-hub/substrate-front-end-template#138
The reason saying hopefully is because this is not the problem in the javascript in the markdown file, but we used to have a <div></div> wrapping a markdown code block. The whole content is then sent to crowdin for translation and sent back. So the not-so-legal syntax (having markdown code block inside html tag) got misinterpretted along the way and missed the punctuation.
=> Hopefully fix the javascript that missed a punctuation in a codeblock

docs/knowledgebase/advanced/codec.md
Gossamer is a host implementation, hard to use just SCALE from it. A standalone Go SCALE codec is a better fit imo.
=> Replace Gossamer with specific Go implementation

docs/tutorials/build-a-dapp/front-end.md
Adding `yarn install` instruction, so ppl for sure would have run it (re: substrate-developer-hub/substrate-front-end-template#139)
=> Add `yarn install` instruction for running front-end template

website/pages/en/index.js
It is (unfortunately) over now 😭 
Possibly replace linking to the replays instead (VERY good btw 🥳 )?
=> remove sub0 registration annoucment

docs/tutorials/create-a-pallet.md
This is a valuable resource to get more under the hood on FRAME for those that are interested:
https://github.com/paritytech/substrate/tree/master/frame/example
This PR suggests one place to reference, I would think it might fit more in the body of the tutorial here... Open to any ideas 😁 
- [?] Does it follow our style guide?
- [?] Do links go to rustdocs or devhub articles rather than code?
=> highlight substrate FRAME example

docs/knowledgebase/integrate/chain-spec.md
This PR change the `Extension` heading in the chain spec KB article from H2 to H3. This makes sense because the extension is part of the client spec. This also sidesteps the question that I had when reading the article
> If there are _two_ parts of the spec, like the text says, then why are there three subheadings.
=> Minor structural fix to chain spec article

docs/tutorials/start-a-private-network/customchain.md
note: this link goes to code, but could also point directly to the docs instead: https://docs.rs/jsonrpc-core/ or https://substrate.dev/rustdocs/v2.0.0/jsonrpc_core/index.html
=> chage broken link to proper one for jsonrpc-proxy

docs/tutorials/start-a-private-network/alicebob.md
Alices port number is explicitly set to 9945 when starting the node.
=> Fix Alice's port number

.circleci/config.yml, CONTRIBUTING.md, crowdin.yaml, readme.md, scripts/deploy-staging, translation.md, website/languages.js
This PR:
- updates multilingual setting, containing simplified chinese, traditional chinese, japanese, and spanish.
- updates the staging deployment flow
- crowdin cli used is updated from crowdin2 to crowdin3.
- updates readme on using crowdin and multilingual contribution
Currently, the staging site is deployed at: 
https://devhub-maindocs.herokuapp.com
*(Username and password are sent in the **devhub** element channel)*
It has the git commit hash specifying which version of source it is built from.
Currently it builds from my private repo (https://github.com/jimmychu0807/devhub-maindocs), because it requires admin access of the repo to connect to Heroku. If this PR looks good and merge to `source` branch, I will work with the admin to have Heroku connects to devhub canonical repo.
=> Resume Staging Deployment & Multilingual Update

.circleci/config.yml, scripts/deploy-staging
Fix #785 
@danforbes this is the (hopefully the last) issue to fix the deployment issue. It is because the key I used is for my personal repo, not substrate-devhub repo. It is now deployed at: 
https://devhub-maindocs.herokuapp.com/index.html
Note the git commit hash in the site (on the site title) matches with the last commit in this PR.
=> Final fix to deploy to staging of devhub-maindocs

docs/knowledgebase/runtime/fees.md, website/sidebars.json
The context is here:
https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/796
@tomusdrw made a great writeup on off-chain indexing, I will be expanding it tomorrow. So I want to hide the page for now.
=> Hiding off-chain-indexing page for now to be expanded

docs/tutorials/start-a-private-network/customchain.md
=> Fix a typo for the `rpc-methods` flag

docs/knowledgebase/runtime/frame.md
=> fix(documentation): benchmark has incorrect url

docs/tutorials/add-a-pallet/index.md
=> fix github url to instructions section

docs/tutorials/create-your-first-substrate-chain/setup.md
v 2.0.0 did not compile for me on OSX 11.1 and rust 14.9 and this bump fixed it as described here https://stackoverflow.com/a/65756888/316729
=> switch to version 2.0.1 of the node template

docs/index.md
The previous link pointed to the "executor" page, which doesn't contain the "forkless runtime upgrades" and "versioning" sections anymore.
These were moved to the "runtime/upgrades" page.
=> Fix broken links related to upgrades

docs/knowledgebase/smart-contracts/overview.md
I would also remove the (SEAL) parenthesis, since I don't see any references to SEAL anywhere in the documentation or the pallet page. Is this an old/internal name? Is SEAL an acronym for something?
=> Add link to contracts pallet

docs/knowledgebase/advanced/codec.md
Incorrect ranges for Compact/General Integers in documentation
=> Incorrect ranges

docs/knowledgebase/getting-started/windows-users.md
The following commands will not work in windows command prompt:
```
.\bootstrap-vcpkg.bat
.\vcpkg.exe install openssl:x64-windows-static
```
I have updated the text to make it clear the commands should be run in Windows PowerShell
For the following issue: https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/852
=> fixing step 5 instructions

docs/knowledgebase/getting-started/windows-users.md
Adding step for installing the `make` command, which is required to follow the Substrate tutorials. Without `make`, it is not possible to initialize your WebAssembly build environment or compile the node template. 
`make` is required for these commands: 
```
make init
make build
```
For this issue: https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/853
=> Adding step to install make command on Windows

docs/tutorials/add-a-pallet/use-a-pallet.md
Running the `WASM_BUILD_TOOLCHAIN=nightly-2020-10-05 cargo build --release` command on Windows gives the following error:
```
WASM_BUILD_TOOLCHAIN=nightly-2020-10-05 : The term 'WASM_BUILD_TOOLCHAIN=nightly-2020-10-05' is not recognized as the name of a cmdlet, function, 
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ WASM_BUILD_TOOLCHAIN=nightly-2020-10-05 cargo build --release
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (WASM_BUILD_TOOLCHAIN=nightly-2020-10-05:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
```
I have suggested removing `WASM_BUILD_TOOLCHAIN=nightly-2020-10-05` so that the command …
=> Command does not work on Windows

docs/tutorials/add-a-pallet/import-a-pallet.md
'SKIP_WASM_BUILD=1' is not recognized as the name of a cmdlet, function, script. This issue: https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/856
Getting an error when running `SKIP_WASM_BUILD=1 cargo check -p node-template-runtime` on the final step of this tutorial: https://substrate.dev/docs/en/tutorials/add-a-pallet/import-a-pallet
```
SKIP_WASM_BUILD=1 : The term 'SKIP_WASM_BUILD=1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the 
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ SKIP_WASM_BUILD=1 cargo check -p node-template-runtime
+ ~~~~~~~~~~~~~~~~~
+ CategoryInfo          : ObjectNotFound: (SKIP_WASM_BUILD=1:String) [], …
```
=> Fix for issue 856

docs/tutorials/build-a-dapp/pallet.md
Assuming I'm correct that traits should be added to lib.rs, we might indicate that to the reader?
=> add guidance on which file to edit

website/pages/en/index.js
Disabling top banner for two weeks to prepare for voting process.  Banner will be enabled again once the voting starts.
=> removing decoded ad per Marcomms

docs/tutorials/build-a-dapp/pallet.md
The tutorial in "Prepare to build a dApp" section mentions "You should already have version v3.0.0 of the Substrate Developer Hub Node Template", but it seems the code snippets are still from v2.0.0 which are not compatible with v3.0.0 and makes the pallet template fail to compile for node template v3.0.0. Apparently the frame_system::Trait module has been renamed to  frame_system::Config in v3.0.0.
=> Upgrade the template code snippets to v3.0.0 [Tutorial: Prepare to build a dApp]

docs/knowledgebase/advanced/no-hash-collections.md, website/sidebars.json
The reasoning behind their omission is not straightforward. This
document explains the rationale.
=> Add knowledgebase document describing why no Hash collections in sp_std

docs/tutorials/create-a-pallet.md
Closes #887 
Note that the template pallet is still using FRAME v1, and IMHO should be updated to FRAME v2 ASAP - issue on that [here](https://github.com/substrate-developer-hub/substrate-pallet-template/issues/17)
=> update create a pallet to v3

docs/tutorials/start-a-private-network/customchain.md
When I run this I don't see a toolbox tab - just a Developer dropdown to get to the RPC calls - maybe the interface has changed?
maybe the screenshot in the tutorial needs changing?
=> toolbox tab to developer drop down

docs/knowledgebase/getting-started/index.md
[Related to #934](https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/934)
@NukeManDan: As promised here is the change. I'm still not 100% happy with it for a variety of reasons but hopefully this helps. I've checked on WSL2 that we only need 
```console
rustup update
rustup update nightly
rustup target add wasm32-unknown-unknown --toolchain nightly
```
after which we can build "substrate-node-template"
=> Try to improve installation instruction.

.editorconfig, docs/tutorials/start-a-private-network/customchain.md
- close #964 
- also minor edit on `.editorconfig` (It is a good setting to have editor trimming trailing spaces on save).
@NukeManDan The reason is that within the html comment ``, we shouldn't have further markdown syntax, the \`\`\`...\`\`\` code block, otherwise the html parser got mixed up.
=> Fix private network tut page not rendering

docs/knowledgebase/getting-started/index.md, docs/knowledgebase/integrate/subkey.md, docs/tutorials/create-your-first-substrate-chain/setup.md
This makes the install instructions more easy to read through, and pushes troubleshooting to a new section with more details for those that run into problems. 
- ~(optional) reference troubleshooting in other devhub locations~
Open to suggestions and edits on this. Hope this makes builder's lives a bit easier.
=> Update install instructions, new troubleshooting section

docs/knowledgebase/getting-started/windows-users.md
Downloading entire history of git repo is unnecessary just
to install vcpkg. So we only download recent branch.
* This PR is very simple so i am not filling all the templates.
=> Windows Installation: Don't download vcpkg full git history

docs/knowledgebase/getting-started/index.md, docs/knowledgebase/integrate/subkey.md, docs/knowledgebase/runtime/fees.md, website/pages/en/tutorials.js
Closes #984
Note: subkey cannot `insert` keys, only the embedded `key` sub-command in substrate nodes is able to now.
=> Update subkey to v2.0.1 and extend examples

docs/knowledgebase/learn-substrate/off-chain-features.md
@sacha-l when ready, I am happy to port the off-chain worker section (3 articles) from Recipes to the how-to guide in your repo.
Do you think it is ready to transfer the how-to guide ownership from you to substrate-developer-hub so all of us can contribute?
=> Linking back to Substrate Recipes on ocw concrete examples

website/static/js/load.js
Simple Analytics is a cookie-free way for us to collect anonymous site traffic data.  
We are implementing this code alongside google analytics for now.  
Within couple of weeks, we'll be removing Google Analytics and reference to Cloudflare cookie - https://blog.cloudflare.com/deprecating-cfduid-cookie/
=> Adding Simple Analytics script per Marcomms

docs/knowledgebase/runtime/upgrades.md
@apopiak 
Ref https://github.com/paritytech/substrate/pull/8687#issuecomment-831189692
=> Added a note on migration order in runtime upgrade

docs/tutorials/start-a-private-network/customchain.md
Fix #791
This add explanations in the tutorial on how to insert keys using the key subcommand. Knowing this can be really helpful to inject keys before the start of the node.
- [X Is the writing:
=> Add instructions on how to use the "key" subcommand for injecting keys

docs/tutorials/add-a-pallet/configure-a-pallet.md
Weight information for is specified as pallet_balances::weights::SubstrateWeight<Runtime> in code for Balances at runtime/src/lib.rs (Line 249), not () as stated in this current tutorial file. This appears to be a fairly recent change, and is not reflected in either v1 or v2 of the Nicks pallet as shown currently here: https://substrate.dev/docs/en/knowledgebase/runtime/pallets
This might be confusing comparing the pallet_balances implementation and pallet_nicks with a known difference. The wording or comparison may also be affected.
This is the file referenced in the tutorial for verification:
https://github.com/substrate-developer-hub/substrate-node-template/blob/master/runtime/src/lib.rs
Other references in the file, specifically impl pallet_grandpa and impl palet_timestamp both …
=> Update tutorial to match Nicks balances weight type implimentation

docs/knowledgebase/runtime/macros.md, docs/knowledgebase/runtime/storage.md
This is in preparation for the next release since paritytech/substrate#8635 has been merged.
The links to the rustdocs obviously don't work yet since a new release of substrate hasn't been cut yet.
=> Document StorageNMap in the knowledge base

docs/knowledgebase/runtime/storage-nmap.md, docs/knowledgebase/runtime/storage.md
@KiChjang 
A PR for removing links to `StorageNMap` API docs that are not existed yet, saving another copy of the files with link so we can easily revert back.
Related: https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/1013
=> Remove StorageNMap links

website/pages/en/tutorials.js
@sacha-l @NukeManDan 
updated 2021-07-05:
- pending on https://github.com/substrate-developer-hub/cumulus-workshop/issues/80
I think it would be good now to add back cumulus workshop in tutorial page.
=> Adding back cumulus workshop in Tutorials Page

docs/knowledgebase/runtime/pallets.md, docs/tutorials/add-a-pallet/publish-a-pallet.md, docs/tutorials/add-contracts-pallet.md
#1065 Fix the FRAME link in the Runtime Development/Pallets documentation.
#1067 Fix the Custom Pallet Development link in the Add Contracts Pallet tutorial.
#1068 Fix the Tutorials link in the Add Pallet / Publish Your Own Pallet tutorial.
=> Fix 3 links in Pallets documentation, Add Contracts Pallet tutorial and Add Pallet tutorial.

docs/knowledgebase/integrate/polkadot-js.md
The extensions link to GitHub repo was pointing the JS APPS repo.  I corrected it to point to the right place.
=> Update to fix link to wrong repo

docs/tutorials/add-a-pallet/import-a-pallet.md, docs/tutorials/add-contracts-pallet.md, docs/tutorials/build-a-dapp/pallet.md, docs/tutorials/build-permission-network/add-node-authorization-pallet.md
For readers that are going through the tutorials after [#232](https://github.com/substrate-developer-hub/substrate-node-template/pull/234) landed, they are likely to have issues with conflicting/old cargo dependencies such as #1122 , #1117, and #1094, if they inadvertently copy the Cargo.toml snips that were not updated.
This PR updates the tags for the tutorials, leaving only **forkless-upgrade** tutorial out as there is an open PR updating it already: #1118.
ty.
=> Update tutorial's cargo dependencies tags

docs/tutorials/add-contracts-pallet.md
Patch for #1128 
(An attempt to) use hard tabs in rust code blocks
Also uses the .editorconfig specified linting, with max char (soft limit) 100 chars.
Can't seem to get Prettier to play nice with 2 space tabs in MD in the context of code blocks within a numbered list... I guess 3 is OK?
=> Formatting nit picks

docs/knowledgebase/runtime/errors.md
- rust hardtabs
- use rustdocs `latest` throughout
=> minor fixes to errors page

docs/tutorials/forkless-upgrade/scheduled-upgrade.md, docs/tutorials/forkless-upgrade/sudo-upgrade.md
Addresses #1117. Also contains clarifies that the Apps/Explorer might need a refresh to before upgrades show/are usable, as I got quite confused about seeing version 102 of the blockchain, but still getting 500 pUnits as ExistentialDeposit, when I should have gotten 100. Refreshing fixed that.
=> Fix #1117 and clarify about UI refresh.
